from pathlib import Path
import json,hashlib,collections
R=Path('/home/chase/GitHub/RWKV-LH');D=R/'data/experiments/RWKV_READ_PARAMETER_DESCRIPTION_R3_20260912'
s=json.loads((D/'SUMMARY.json').read_text());calls=json.loads((D/'CALL_AUDIT.json').read_text());assert s['gate']['complete']
reg=json.loads((D/'REGISTRATION.json').read_text());gate=s['gate']['passed']
rows=['# 单步读取参数说明 R3：冻结前后对照','','本轮无新的项目级 Agent Strict/completed；所有试验均在一次调用/协议拒绝边界结束，不声明任务完成。诊断工作区 mutation=0；未启动自主定位、多步任务、Coordinator 或训练。','', '## 结果','','| 固定组 | 修改前 | 修改后 |','|---|---:|---:|']
for group,label in [('primary_r1_valid7','R1有效7例×3遍'),('supplement_r2_missing1','R2修正缺失例×3遍（独立）')]:
 b=s['before']['suites'][group];a=s['after']['suites'][group];rows.append(f"| {label} | {b['pass']}/{b['attempts']} | {a['pass']}/{a['attempts']} |")
rows+=['','| 主组轮次 | 修改前 | 修改后 |','|---|---:|---:|']
for b,a in zip(s['before']['suites']['primary_r1_valid7']['repetitions'],s['after']['suites']['primary_r1_valid7']['repetitions']):rows.append(f"| 第{b['repeat']}遍 | {b['pass']}/{b['attempts']} | {a['pass']}/{a['attempts']} |")
rows+=['',f"协议错误：修改前{s['before']['protocol_errors']}，修改后{s['after']['protocol_errors']}；提前final_answer：修改前{s['before']['premature_final']}，修改后{s['after']['premature_final']}。本轮按更严格口径将任何替代读取的final_answer作为提前终止并拒绝，不依赖关键词猜测成功声明。缺失文件的真实FileNotFoundError可通过诊断，但工具success仍为false；没有第二次模型调用，因此不声称已证明异常后的回答能力。",'',f"**预注册门：{'通过' if gate else '未通过'}。** 门槛要求候选第2、3遍两组均全部通过、零协议错误和提前final_answer；基线3/3用例不得退化。实际判定见SUMMARY.json gate。范围仅是这些固定用例，不代表通用读取可靠性或Agent Strict收益。即使通过，本轮不升级到自主定位。",'', '逐例结果：','','| 用例 | 修改前 | 修改后 |','|---|---:|---:|']
for c in reg['cases']:
 b=s['before']['cases'][c['id']];a=s['after']['cases'][c['id']];rows.append(f"| {c['id']} | {b['pass']}/{b['attempts']} | {a['pass']}/{a['attempts']} |")
rows+=['','R1历史18/21与R2历史3/3继续分开保留；R1另外3次夹具无效记录不重评分、不补入新轮分母。本轮收益比较仅来自此次新采的修改前/后固定两组。','', '## 原因核对与唯一修改','','更正旧报告：三次R1原始失败中，两次是end_byte=-1；第三次是max_lines=2048与max_bytes=8192，不是第三次end_byte。完整真实输入/原文/全部token与源SHA见FAILURE_INPUT_OUTPUT_AUDIT.json；三条fixture逐字节保留，旧报告封存不改。','', '原schema已清楚声明path/string/required、start_byte/integer/minimum=0/default=0、max_tokens/integer/256..8192/default=4096，以及additionalProperties=false。因此非法字段属于模型未遵守已有机器合同。自然语言未说明省略规则、inclusive起点/exclusive终点、UTF-8字节边界、EOF、token预算与分页之间的关系；本轮仅澄清这些语义，不把原参数集合说成允许多种解释。','', '唯一生产差异是ActionHarness中read_file工具description和三个字段description。没有新增字段、改变默认值/边界、自动删除或映射非法参数、路径/后缀特判、额外模型调用、parser或stop boundary修改。移除这些description后整个harness.py AST相同，其他生产文件SHA相同。说明从同一工具登记进入完整菜单及既有披露入口；此次真实评测只覆盖完整菜单直接调用路径。','', '本次对照检验的是说明澄清这个整体候选（包括输入token增加），不是对每一句话的独立因果分解。重复样本有限，不能据此保证在新文件、长文本、分页、其他语言、换行形式或异常类别中永不生成非法字段。','', '## 冻结与证据完整性','',f"预注册SHA-256：`{hashlib.sha256((D/'REGISTRATION.json').read_bytes()).hexdigest()}`。在任何模型生成前同时冻结两套客户端；只有说明文本不同，按before→after串行运行，两臂之间没有编辑rwkv_lh/。使用同一份R1执行/scorer脚本、原用例request/workspace、zero State、temperature=0.1/top_p=1/top_k=0及1800输出token预算；每臂21+3次，无语义重试。",f"完整输入token逐项核验：修改前{s['before']['input_exact']}/24，修改后{s['after']['input_exact']}/24。两臂按用例去掉read_file说明后的实际完整输入一致：{s['gate']['paired_inputs_only_read_descriptions_differ']}。每次记录模型/State身份、完整输入/输出token、raw输出、stop原因、commit/rollback和真实观察的父子State绑定。",'']
for arm,label in [('before','修改前'),('after','修改后')]:
 c=[x for x in calls if x['arm']==arm];rows.append(f"- {label}：输入tokens {min(x['input_tokens'] for x in c)}–{max(x['input_tokens'] for x in c)}；输出tokens {min(x['output_tokens'] for x in c)}–{max(x['output_tokens'] for x in c)}；stop原因 {dict(collections.Counter(x['finish_reason'] for x in c))}。")
rows+=['','服务器未重新部署：项目132文件、engine6393文件匹配原上传manifest，模型/服务build/tokenizer身份未变。首次5秒本地健康探针超时，后续本地及SSH探针成功且身份核验通过，之后才开始评分调用；基础设施检查不计模型失败。服务器未用Git。','', '## 工程验证与保留状态','','真实失败回归修改前3 failed/1 passed，修改后4 passed；既保持非法输出拒绝，又检查实际模型输入获得新说明。Harness行为回归覆盖默认值、UTF-8边界、半开区间、EOF和越界。完整tests/：1512 passed、0 skipped、245.08秒；按AGENTS安装依赖和Chromium。','', '原有5个未提交文件逐文件SHA保持不变，不纳入本轮提交。未训练、未新建data/datasets版本、未访问Holdout、未更新GitHub、未恢复项目级A/B。完整初始/生成/State/工作区/SQLite与日志在RAW_EVIDENCE.tar.gz；冻结客户端在FROZEN_SOURCE_SNAPSHOTS.tar.gz；目录各文件SHA见SHA256SUMS.json。','', '后续若进入自主定位，只增加“不提供准确路径”这一变量，由RWKV自行搜索、读取和回答，不引入Coordinator。本轮没有开始该阶段。']
(D/'REPORT.zh-CN.md').write_text('\n'.join(rows)+'\n');print('report_sha256',hashlib.sha256((D/'REPORT.zh-CN.md').read_bytes()).hexdigest())
