from pathlib import Path
import json,hashlib,collections
R=Path('/home/chase/GitHub/RWKV-LH');D=R/'data/experiments/RWKV_READ_PARAMETER_DESCRIPTION_R4_20260912'
s=json.loads((D/'SUMMARY.json').read_text());calls=json.loads((D/'CALL_AUDIT.json').read_text());assert s['gate']['complete']
reg=json.loads((D/'REGISTRATION.json').read_text());gate=s['gate']['passed']
lines=['# 简短读取参数说明 R4：固定用例前后验证','','没有新项目级Agent Strict/completed；诊断mutation=0；均在一次调用或协议拒绝边界截停，不声明任务完成。没有进入自主定位、多步任务或Coordinator。','', '## 前后结果','','| 固定组 | 本轮新采原说明 | 本轮简短说明 |','|---|---:|---:|']
for group,label in [('primary_r1_valid7','R1有效7例×3遍'),('supplement_r2_missing1','R2修正缺失例×3遍（独立）')]:
 b=s['before']['suites'][group];a=s['after']['suites'][group];lines.append(f"| {label} | {b['pass']}/{b['attempts']} | {a['pass']}/{a['attempts']} |")
lines+=['','| 主组遍次 | 原说明 | 简短说明 |','|---|---:|---:|']
for b,a in zip(s['before']['suites']['primary_r1_valid7']['repetitions'],s['after']['suites']['primary_r1_valid7']['repetitions']):lines.append(f"| {b['repeat']} | {b['pass']}/{b['attempts']} | {a['pass']}/{a['attempts']} |")
lines+=['',f"协议错误{s['before']['protocol_errors']}→{s['after']['protocol_errors']}，提前final_answer {s['before']['premature_final']}→{s['after']['premature_final']}。不存在文件的正确读取尝试以真实FileNotFoundError通过诊断，其工具success仍为false。任何替代必要读取的final_answer均按更严格口径算提前终止；没有生成观察后的回答，不声称已验证回答理解或任意成功声明。",'',f"**预注册门{'通过' if gate else '未通过'}。** 门要求最后两遍两组全部通过，零协议错误与提前final_answer，且原说明3/3用例不退化。门只适用于这些固定输入，不证明普遍稳定；本轮不自动升级任务。",'', '| 用例 | 原说明 | 简短说明 |','|---|---:|---:|']
for c in reg['cases']:
 b=s['before']['cases'][c['id']];a=s['after']['cases'][c['id']];lines.append(f"| {c['id']} | {b['pass']}/3 | {a['pass']}/3 |")
lines+=['','## 完整历史与原因界限','','R1历史有效18/21、独立R2历史3/3分别保留；R1另外3次夹具无效记录未替换或重评分。原始三次R1参数失败实际为两次end_byte=-1、一次max_lines=2048与max_bytes=8192，旧“全部end_byte”汇总以R3的完整输入输出审计更正。','', '本任务先测的R3较长说明明确提到了非法结束字段：新采主组19/21→14/21、独立补充3/3→2/3、协议错误2→8，NO_KEEP。R3不是本轮基线，不能省略失败候选、合并分母或只展示获胜文案。R4重新采集了原说明与简短说明两个完整固定组。','', '原schema的合法字段、类型、required、范围和additionalProperties=false本来明确；自然语言缺少省略、起止范围、EOF和token预算语义。R3证明“加上更详细的禁止说明”不充分。R4仅列合法输入及正向语义，不在输入描述里列举非法字段名或负值示例。本轮检验的是该说明整体（措辞和长度都改变），不能单独断言负向提示、注意力或训练分布是已证实的内部原因。','', '唯一生产变化仍是read_file登记的description及参数description：path必填字符串；start_byte可省略默认0、inclusive UTF-8字节偏移、字符边界至decoded text EOF；max_tokens可省略默认4096、整数256..8192、token单位；结束位置由工具计算且不包含。字段、类型、默认值、范围、parser、normalizer、Harness执行、stop boundary均未改变，不接纳或重写非法参数，不按README或后缀特判，没有程序代选操作或参数。','', '## 冻结、State与运行证据','',f"预注册SHA `{hashlib.sha256((D/'REGISTRATION.json').read_bytes()).hexdigest()}`。在模型运行前同时冻结原说明/候选客户端，AST忽略read_file说明后完全相同，其他生产文件SHA相同。按before→after，每臂主组21次+独立补充3次；原request、workspace、scorer、13.3B模型、zero State、temperature0.1/top_p1/top_k0、1800输出token上限不变。没有语义重试或新增模型调用。",f"完整输入token逐项核验：before {s['before']['input_exact']}/24、after {s['after']['input_exact']}/24；去掉唯一说明差异后实际输入一致：{s['gate']['paired_inputs_only_read_descriptions_differ']}。每例三遍输入相同与逐次raw输出、生成token、模型/State身份、commit/rollback、实际观察父子State交接见CALL_AUDIT.json及RAW_EVIDENCE.tar.gz。",'']
for arm in ['before','after']:
 cc=[c for c in calls if c['arm']==arm];lines.append(f"- {arm} input tokens {min(c['input_tokens'] for c in cc)}–{max(c['input_tokens'] for c in cc)}；output tokens {min(c['output_tokens'] for c in cc)}–{max(c['output_tokens'] for c in cc)}；停止原因 {dict(collections.Counter(c['finish_reason'] for c in cc))}。")
lines+=['','基线offset-1-r1在生成返回后的commit遭本地SSH转发断开；远端健康。恢复转发后，现有Native恢复以原request_id与digest安全重发commit一次，只有一次generation，后续观察提交成功；原始错误和恢复事件完整保留，不算模型重新采样或删除失败。监听消失的原因未知，未修改网络代码。服务器项目132/engine6393文件均与原上传manifest匹配，无服务器Git或重新部署。','', '## 回归和当前范围','','回归保存原R1三份原文及R3两个真实新增退化样本。5 failed/1 passed→6 passed：候选说明确实进入模型输入，非法输出仍在Harness执行前拒绝；实际Harness测试覆盖默认值、UTF-8边界、半开范围、EOF和越界。候选源码完整tests/：1514 passed、0 skipped、241.68秒。工程回归不是模型能力得分。','', '这两轮是有限候选搜索，原基线也表现出采样波动。没有独立新用例泛化检验，长文件分页、其他换行形式、目录/权限异常、定位和回答仍未在本轮覆盖。只据冻结门报告当前固定用例，不扩大结论。','', '原5个未提交文件逐文件SHA保持不变。未训练、新建datasets版本、访问Holdout、更新GitHub或恢复项目级A/B。原始run/SQLite/输入输出/State/工作区/日志封装于RAW_EVIDENCE.tar.gz，两套冻结客户端见FROZEN_SOURCE_SNAPSHOTS.tar.gz，逐文件SHA见SHA256SUMS.json。']
(D/'REPORT.zh-CN.md').write_text('\n'.join(lines)+'\n');print('report_sha256',hashlib.sha256((D/'REPORT.zh-CN.md').read_bytes()).hexdigest())
