from pathlib import Path
import json,hashlib
R=Path('/home/chase/GitHub/RWKV-LH');D=R/'data/experiments/RWKV_SINGLE_READ_DIAGNOSTIC_R1_20260912'
summary=json.loads((D/'SUMMARY.json').read_text());rr=json.loads((D/'RESULTS.json').read_text());assert len(rr)==24
valid=[r for r in rr if r['case']!='missing-2'];repeat=json.loads((D/'REPEATABILITY.json').read_text())
lines=['# 单步读取诊断 R1（冻结结果）','','本轮没有新的项目级 Agent 评测：Strict / completed 不适用；诊断工作区 mutation 为 0。每次到一次工具调用或协议拒绝边界即结束，不将截停称为任务完成。R5 历史仍为 Strict/外部通过 0/12，completed 1/12 且错误完成，其余 11 题中断；未续跑 A。','',f"原冻结评分：{summary['diagnostic_pass']}/24；其中 missing-2 的 3 次夹具无效，原分数不重写。有效能力证据为 {sum(r['pass'] for r in valid)}/21（{sum(r['pass'] for r in valid)/21:.2%}），协议拒绝 {sum(bool(r['protocol_error']) for r in valid)} 次。原 24 次实际工具成功 {summary['tool_success']} 次；异常路径通过与工具成功严格分开。",'','| 场景 | 有效通过 | 结论 |','|---|---:|---|']
for name,title in [('full_text','README 全文'),('full_code','代码全文'),('offset','恰好 EOF 的空读取'),('missing','不存在的 server.py')]:
 x=[r for r in valid if r['case'].startswith(name)]
 lines.append(f"| {title} | {sum(r['pass'] for r in x)}/{len(x)} | {'本次三遍复现' if all(r['pass'] for r in x) else '不稳定'} |")
lines+=['','## 可复核证据','',f"- 预注册 SHA-256：`{hashlib.sha256((D/'REGISTRATION.json').read_bytes()).hexdigest()}`。8 例×3 次；从 R5 实际读取记录按顺序选取四类各两个唯一 case/path/offset。先冻结再生成。",'- 调用现有 LongHorizonModel.next_command、原完整菜单、原 parser/stop boundary 和 Harness；没有 Coordinator、Selector、工具资格过滤或语义重试。请求是历史动作的受控单步简化，不是角色训练数据。',f"- 完整输入 token 与根 State 文本+BOS 逐项一致 {summary['input_token_exact']}/24；每例三遍输入完全相同：{all(v['identical_inputs'] for v in repeat.values())}。zero State、完整输入/输出 token、原文、commit/rollback、观察 State 父子关系保存在 runs/*/state_snapshot.json、model_trace.jsonl 和 RAW_EVIDENCE.tar.gz。",'- 成功执行后将真实 observation 通过生产 builder 追加一次；没有再调用模型解读结果。因此只证明观察进入 State，未证明模型理解异常、停止循环或生成可信 Final。', '- 服务恢复的是既有 SSH 转发；服务器项目 132 文件、engine 6393 文件均匹配上传 manifest，manifest 与本地冻结文件 SHA 一致。没有服务器 Git、部署、训练或 GitHub 更新。','', '## 根因与全局影响','','本轮直接可归因失败是 RWKV 生成 read_file 合同不允许的参数。原工具只声明 path / start_byte / max_tokens；失败原文生成 end_byte=-1。所有输入完整、自然 stop，不能把这三次拒绝归因于输入截断或输出预算耗尽。相同输入的三遍结果不同，尚不能证明内容长度、语言、文件类型或模板哪一项是潜在原因。','', 'R5 全部 12 题审计共 159 次 read_file、40 个原始 case/path/offset 组合：153 次工具成功、6 次 FileNotFoundError。153 次成功均与匹配 SHA 的实际文件字节一致；105 次从零、15 次非零内部偏移、33 次恰好 EOF。历史拒绝已出现 max_bytes、max_lines、end_byte、start_after 等非法参数。这是跨用例的生成合同遵循问题，不支持按路径或后缀特判。历史“147 已核对、6 未匹配”是分析脚本未消除 ./ 路径写法导致的中间审计值，已按 Path 同一文件身份核实，未修改原历史评分。','', '## 夹具缺陷与修复隔离','','missing-2 使用了 R5 最终工作区，而源事件 67 的 A00014 读取 index.html 不存在之后，事件 71 的 A00015 创建了该文件。RWKV 在本轮正确读到文件，不是模型失败。全部 3 次被标为 fixture_invalid_not_model_failure，FIXTURE_INVALIDITY.json 保留因果证据。本轮冻结原评分不变；后续 RWKV_SINGLE_READ_FIXTURE_REPAIR_R2_20260912 使用已有公开初始 workspace 单独复测，不替换本轮分母。','', '## 最小后续修复建议','','优先在唯一 read_file 工具描述中明确合法输入字段及 max_tokens / next_start_byte 的语义，作为待验证候选；不接受或改写 end_byte、max_bytes 等模型输出。保持完整工具菜单和 RWKV 自选调用，仍用本轮有效固定用例三遍检验。候选落地必须先有失败再通过的合同/真实调用回归，并另行预注册同一单步范围的验证；当前没有修改生产提示、parser、预算或模型 State。','', '这只是 7 个有效样本的有限重复证据。代码/EOF/缺失文件在这些输入上的稳定表现不能推广为通用阅读能力；内部偏移、多字节非法偏移、长文件分页、空文件、目录/权限异常尚未在新模型诊断覆盖。README 不稳定未解决，不进入自主定位或修改阶段。','', '## 工程与复现','','完整 tests/：1508 passed、0 skipped、244.83 秒；环境按 AGENTS 准备并安装 Chromium。入场时 5 个已跟踪未提交文件逐文件 SHA 未变，本轮不将它们纳入提交。实验脚本在 temp/，相关生产输入/归一化/Harness/State 路径和测试索引见 ENGINEERING_VALIDATION.json。','', '复现入口：先核验 REGISTRATION.json source_pins 和 SHA256SUMS.json；原封存目录不能续写。独立注册新输出目录后使用同一 run_single_read_diagnostic_r1_20260912.py 输入 builder 和执行路径。RAW_EVIDENCE.tar.gz 保存原始 run、SQLite、完整 trace 与验证日志，工作区和原始文件也保留在本地。']
(D/'REPORT.zh-CN.md').write_text('\n'.join(lines)+'\n')
print('report',hashlib.sha256((D/'REPORT.zh-CN.md').read_bytes()).hexdigest())
